apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsheet-exporter
  labels:
    app: gsheet-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsheet-exporter
  template:
    metadata:
      labels:
        app: gsheet-exporter
    spec:
      containers:
      - name: registry
        image: registry:2.7.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: docker-registry-storage
        resources:
          requests:
            memory: "2G"
      - name: exporter
        image: tmaxcloudck/gsheet-exporter:dev
        imagePullPolicy: Always
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secret/key.json
          - name: TARGET_SHEETS
            value: '1zBHhKvdz5sv2HZFWGcbsvAVFspQAvm_yEYtY9ZffSZc;CK1!C2:D,1zBHhKvdz5sv2HZFWGcbsvAVFspQAvm_yEYtY9ZffSZc;CK2!C2:D'
          - name: REGISTRY_URL
            value: localhost:5000
          - name: DOCKER_CRED
            valueFrom:
              secretKeyRef:
                name: regcred
                key: dockerio
          - name: QUAY_CRED
            valueFrom:
              secretKeyRef:
                name: regcred
                key: quayio
          - name: GCR_CRED
            valueFrom:
              secretKeyRef:
                name: regcred
                key: gcr
          - name: ARCHIVE_PATH
            value: /data
          - name: SCP_DEST
            value: ck-ftp@192.168.1.150:/home/ck-ftp/k8s/install/offline/supercloud-images
          - name: SCP_PASS
            value: ck-ftp
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "4G"
        volumeMounts:
          - name: docker-registry-storage
            mountPath: /data
          - name: gcp-credential
            mountPath: /secret
            readOnly: true
      volumes:
      - name: docker-registry-storage
        persistentVolumeClaim:
          claimName: gsheet-exporter-registry-pvc
      - name: gcp-credential
        secret:
          secretName: gcpcred
          items:
            - key: key.json
              path: key.json
---
apiVersion: v1
kind: Service
metadata:
  name: gsheet-exporter
spec:
  type: NodePort
  selector:
    app: gsheet-exporter
  ports:
    - name: docker
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30800
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gsheet-exporter-registry-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
