apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-exporter
  labels:
    app: docker-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-exporter
  template:
    metadata:
      labels:
        app: docker-exporter
    spec:
      containers:
      - name: registry
        image: registry:2.7.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: docker-registry-storage
        resources:
          requests:
            memory: "2G"
      - name: exporter
        image: tmaxcloudck/gsheet-exporter:dev
        imagePullPolicy: Always
        env:
          - name: SHEET_URL
            value: https://docs.google.com/spreadsheets/d/1zBHhKvdz5sv2HZFWGcbsvAVFspQAvm_yEYtY9ZffSZc/edit#gid=769436284
          - name: SHEET_IDX
            value: "0"
          - name: COL_NUM
            value: "1"
          - name: ROW_FROM
            value: "2"
          - name: REGISTRY_URL
            value: localhost:5000
          - name: DOCKER_CRED
            valueFrom:
              secretKeyRef:
                name: regcred
                key: dockerio
          - name: QUAY_CRED
            valueFrom:
              secretKeyRef:
                name: regcred
                key: quayio
          - name: GCR_CRED
            valueFrom:
              secretKeyRef:
                name: regcred
                key: gcr
          - name: ARCHIVE_PATH
            value: /data
          - name: SCP_DEST
            value: ck-ftp@192.168.1.150:/home/ck-ftp/k8s/install/offline/supercloud-images
          - name: SCP_PASS
            value: ck-ftp
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "4G"
        volumeMounts:
          - mountPath: /data
            name: docker-registry-storage
      volumes:
      - name: docker-registry-storage
        persistentVolumeClaim:
          claimName: docker-registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: docker-exporter
spec:
  type: NodePort
  selector:
    app: docker-exporter
  ports:
    - name: docker
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30800
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
