apiVersion: batch/v1
kind: Job
metadata:
  name: image-sync-request
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          command:
            - "/bin/sh"
            - "-c"
            - |
              curl -X "POST" "http://192.168.0.3:30800" \
              -H 'Content-Type: application/json' \
              -d '{ \
              "url": "<SHARED_GOOGLE_SHEET_URL>", \
              "num": "<SHEET_INDEX(FROM_0)>", \
              "col": <COLUMN_INDEX_NUMBER>, \
              "row": <ROW_INDEX_TO_START> \
              }'
      restartPolicy: Never
  backoffLimit: 4